// --- CONFIGURACIÓN DE ADMINISTRADOR ---
const ADMIN_PASS = "2418613";

// --- BASE DE DATOS ECUADOR ---
const DATA_ECUADOR = {
    "🇪🇨 Comida Típica": [
        ["Encebollado", "Levanta muertos con yuca y albácora"],
        ["Cuy Asado", "Mascota o manjar andino"],
        ["Bolón de Verde", "Desayuno redondo de plátano y queso/chicharrón"],
        ["Fanesca", "Sopa santa de 12 granos"],
        ["Guatita", "Mondongo con salsa de maní"],
        ["Ceviche de Camarón", "Sopa fría roja y ácida con marisco"],
        ["Hornado", "Cerdo entero asado con piel galleta"],
        ["Salprieta", "Polvo manabita delicioso de maní y maíz"],
        ["Morocho", "Bebida blanca espesa con maíz"],
        ["Chaulafan", "El arroz chino de aquí"],
        ["Yahuarlocro", "Sopa de papas que lleva sangre"],
        ["Tigrillo", "Verde majado con huevo y queso (Zaruma)"],
        ["Locro de Papa", "Sopa cremosa con queso y aguacate"],
        ["Tripa Mishqui", "Intestinos asados al carbón en la calle"],
        ["Humitas", "Masa de maíz dulce en su propia hoja"],
        ["Chugchucaras", "Plato de Latacunga con todo lo del cerdo"],
        ["Seco de Chivo", "Guiso fuerte (que a veces es borrego)"],
        ["Muchines de Yuca", "Fritos de yuca con queso dentro"],
        ["Corviche", "Masa frita de verde con pescado"],
        ["Cazuela de Pescado", "Horneado de verde y maní en barro"],
        ["Viche Manabita", "Sopa espesa de pescado y maní"],
        ["Empanada de Viento", "Grande, llena de aire y azúcar"],
        ["Espumilla", "Parece helado pero no se derrite (guayaba)"],
        ["Colada Morada", "Bebida de difuntos con frutas y harina negra"],
        ["Pan de Yuca", "Bolita de almidón elástica y con queso"],
        ["Chifles", "Rodajas finas y fritas de plátano"],
        ["Patacones", "Plátano verde aplastado y vuelto a freír"],
        ["Maito", "Pescado envuelto en hojas (Amazonía)"],
        ["Ayampaco", "Plato amazónico asado en hoja"],
        ["Helado de Paila", "Batido a mano en olla de bronce (Ibarra)"],
        ["Llapingachos", "Tortillas de papa con huevo y chorizo"],
        ["Fritada", "Carne de cerdo cocinada en paila de bronce"],
        ["Choclo con Queso", "Mazorca tierna con queso fresco"],
        ["Repe Lojano", "Sopa cremosa de guineo verde"],
        ["Cecina", "Carne de cerdo ahumada y fina (Loja)"],
        ["Caldo de Salchicha", "Sopa negra con vísceras y sangre (Manguera)"],
        ["Encocado", "Mariscos en salsa de coco (Esmeraldas)"],
        ["Cevichocho", "Ceviche serrano de chochos"],
        ["Tortillas de Tiesto", "Pan plano asado en barro"],
        ["Pájaro Azul", "Licor de Guaranda con gallina"],
        ["Mistelas", "Dulces con licor líquido dentro"],
        ["Rosero", "Bebida quiteña con frutas y flores"],
        ["Come y Bebe", "Ensalada de frutas con jugo"]
    ],
    "🏔️ Lugares Típicos": [
        ["Cotopaxi", "Volcán de cono de nieve perfecto"],
        ["Montañita", "Surf, fiesta y extranjeros"],
        ["Mitad del Mundo", "Un pie en cada hemisferio (Latitud 0)"],
        ["Galápagos", "Tortugas gigantes y teoría de la evolución"],
        ["El Panecillo", "Virgen gigante con alas en Quito"],
        ["Malecón 2000", "Paseo moderno junto al río Guayas"],
        ["Baños de Agua Santa", "Cascadas, deportes extremos y dulces"],
        ["Quilotoa", "Laguna esmeralda dentro de un cráter"],
        ["Chimborazo", "El punto más cercano al sol"],
        ["La Ronda", "Calle colonial bohemia en Quito"],
        ["Nariz del Diablo", "Tren difícil en montaña empinada"],
        ["Parque La Carolina", "El pulmón verde del norte de Quito"],
        ["Catedral de Cuenca", "Iglesia con cúpulas celestes"],
        ["Ingapirca", "Ruinas incas con templo solar"],
        ["Laguna de Cuicocha", "Laguna con dos islotes en el centro"],
        ["Parque Nacional Yasuní", "Selva con máxima biodiversidad"],
        ["El Cajas", "Páramo frío lleno de lagunas"],
        ["Puerto Ayora", "Ciudad principal de Santa Cruz"],
        ["Los Frailes", "Playa virgen en forma de media luna"],
        ["Las Peñas", "Barrio colorido y antiguo con escalinatas"],
        ["Mindo", "Bosque nublado, mariposas y aves"],
        ["Papallacta", "Aguas termales en el frío páramo"],
        ["Salinas", "Edificios blancos y playa popular"],
        ["Atacames", "La playa de la fiesta y caipiriñas"],
        ["Tena", "Capital de la canela y entrada a la selva"],
        ["Puyo", "Ciudad amazónica de Pastaza"],
        ["Isla Santay", "Isla ecológica frente a Guayaquil"],
        ["Parque Histórico", "Zoológico y casas antiguas en Samborondón"],
        ["Teleférico de Quito", "Sube al Pichincha en góndola"],
        ["Plaza de los Ponchos", "Mercado artesanal gigante en Otavalo"],
        ["Laguna de Yambo", "La laguna encantada en la Panamericana"],
        ["Vilcabamba", "Valle de la longevidad"],
        ["Zaruma", "Ciudad de oro y patrimonio"],
        ["Ruinas de Cochasquí", "Pirámides truncas preincas"],
        ["Podocarpus", "Parque nacional en el sur"],
        ["Cuyabeno", "Reserva de producción faunística inundada"]
    ],
    "🍺 Farra y Chupa": [
        ["Pilsener", "La rubia que une al país"],
        ["Club Verde", "La cerveza premium de etiqueta esmeralda"],
        ["Zhumir", "Espíritu azuayo en botella"],
        ["Pájaro Azul", "Licor turquesa de Guaranda"],
        ["Canelazo", "Bebida caliente con naranjilla y puntas"],
        ["Norteño", "Aguardiente popular de la costa"],
        ["Biela", "Sinónimo callejero de cerveza"],
        ["Jager", "Licor de hierbas oscuro para la farra"],
        ["Puntas", "Alcohol artesanal fuerte sin etiqueta"],
        ["Caña Manabita", "Licor fuerte orgullo de Manabí"],
        ["Michelada", "Cerveza con limón y sal"],
        ["Chicha", "Bebida fermentada de maíz"],
        ["Guanchaca", "Aguardiente rústico de caña"],
        ["Cristal", "Aguardiente seco y transparente"],
        ["Switch", "Bebida barata de colores neón"],
        ["Rompe Colchón", "Coctel potente o sopa de mariscos"],
        ["Vino Hervido", "Vino caliente con especias"],
        ["Currincho", "Licor manabita muy fuerte"],
        ["Draque", "Aguardiente con agua caliente y limón"],
        ["Caipiriña", "Coctel brasileño adoptado en la playa"],
        ["Mojito", "Coctel con menta, muy popular"],
        ["Shot", "Trago corto y rápido"],
        ["Barra Libre", "Pagas entrada y tomas todo"],
        ["After Party", "La fiesta después de la fiesta"],
        ["Chiva", "Bus rumbero sin ventanas"]
    ],
    "🗣️ Jerga Ecuatoriana": [
        ["Chuchaqui", "Malestar físico después de beber"],
        ["Cholo", "Identidad mestiza o insulto clasista"],
        ["Aniñado", "Persona con dinero que vive en burbuja"],
        ["Mandarina", "Hombre dominado por su pareja"],
        ["Bacán", "Algo muy bueno, chévere o excelente"],
        ["Acolitar", "Verbo para ayudar o acompañar"],
        ["Cachas", "Verbo de entender (¿Entiendes?)"],
        ["Lámpara", "Algo muy vistoso o situación bochornosa"],
        ["Caleta", "Casa o lugar donde vives"],
        ["Camello", "Trabajo o labor diaria"],
        ["Chapa", "Policía o guardia"],
        ["Choro", "Ladrón o delincuente"],
        ["Sapo", "Persona muy viva, curiosa o corrupta"],
        ["Pelada", "Novia o chica"],
        ["Suco", "Persona rubia o de pelo claro"],
        ["Mushpa", "Tonto o lento (palabra kichwa)"],
        ["Visaje", "Hacer muecas o bulto innecesario"],
        ["Lamparoso", "Alguien que le gusta llamar la atención"],
        ["De ley", "Afirmación rotunda, seguro"],
        ["Canguil", "Palomitas de maíz"],
        ["Once", "La comida de la tarde (café con pan)"],
        ["Jama", "Comida o alimento"],
        ["Ruco", "Dormido profundamente o viejo"],
        ["Pana", "Amigo cercano"],
        ["Yunta", "Mejor amigo inseparable"],
        ["Ñaño", "Hermano de sangre o de cariño"],
        ["Vajilla", "Caer mal o ser pesado"],
        ["Foca", "Vergüenza pública"],
        ["Amorbidae", "Tacaño, que no suelta dinero"],
        ["Encamador", "Mentiroso o hablador"],
        ["Entucar", "Golpear o meter con fuerza"],
        ["Lleca", "La calle"],
        ["Paco", "Otra forma de decir policía"],
        ["Pipón", "Barrigón o vago del estado"],
        ["Tuco", "Fuerte, musculoso o grande"],
        ["Vaina", "Cosa, asunto o problema"],
        ["Sorbete", "Pajita para beber"],
        ["Guachimán", "Guardia de seguridad (Watchman)"],
        ["Llucho", "Desnudo o sin ropa"],
        ["Chauchera", "Trabajo pequeño o monedero"]
    ],
    "👻 Leyendas y Mitos": [
        ["La Llorona", "Busca a sus hijos cerca de los ríos"],
        ["El Duende", "Enamora a mujeres de pelo largo y trenza crines"],
        ["La Dama Tapada", "Mujer bella con calavera bajo el velo"],
        ["El Padre Almeida", "Salía de farra pisando al Cristo"],
        ["Cantuña", "Pactó con el diablo para construir una iglesia"],
        ["Mariangula", "Niña que robó tripas de un muerto"],
        ["El Tin Tin", "Ser mitológico de la costa que embaraza mujeres"],
        ["La Tunda", "Mujer de la selva con pata de molinillo"],
        ["El Chuzalongo", "Enano de los páramos que ataca mujeres"],
        ["Posorja", "Vidente legendaria de la costa"],
        ["La Caja Ronca", "Procesión fantasmal con ruidos extraños"],
        ["El Gallo de la Catedral", "Gallo de metal que atacó a un borracho"]

    ],
    "🌟 Famosos Ecuatorianos": [
        ["Jefferson Pérez", "Marchista olímpico, medalla de oro"],
        ["Richard Carapaz", "Ciclista, la Locomotora del Carchi"],
        ["Chito Vera", "Peleador de la UFC, orgullo manabita"],
        ["Enner Valencia", "Goleador histórico de la selección"],
        ["Julio Jaramillo", "El Ruiseñor de América (Pasillo)"],
        ["Jaime Roldós", "Presidente que murió en avioneta"],
        ["Eloy Alfaro", "El Viejo Luchador, líder liberal"],
        ["Eugenio Espejo", "Prócer, médico y periodista colonial"],
        ["Delfín Quishpe", "Cantante de las Torres Gemelas"],
        ["Sharon la Hechicera", "Diva de la tecnocumbia"],
        ["Antonio Valencia", "Jugó en el Manchester United"],
        ["Oswaldo Guayasamín", "Pintor de la ira y la ternura"],
        ["Matilde Hidalgo", "Primera mujer en votar en A. Latina"],
        ["Tránsito Amaguaña", "Líder indígena histórica"],
        ["Gerardo Morán", "El más querido (cantante)"],
        ["Don Day", "Youtuber y actor"],
        ["Érika Vélez", "Actriz y presentadora famosa"],
        ["Alex Aguinaga", "El maestro, leyenda del fútbol"],
        ["Ivan Kavanagh", "No, Ivan Vallejo (Alpinista)"],
        ["Andrés Guschmer", "Periodista deportivo y político"]
    ]
};

// --- BASE DE DATOS NORMAL ---
const DATA_NORMAL = {
    "💻 Ingeniería TI": [
        ["Algoritmo", "Pasos ordenados para resolver un problema"],
        ["Base de Datos", "Almacén organizado de información digital"],
        ["Servidor", "Computadora central que provee datos a otras"],
        ["Nube", "Almacenamiento en internet, no en tu disco"],
        ["Firewall", "Pared de fuego que bloquea accesos malos"],
        ["Python", "Lenguaje de programación con nombre de serpiente"],
        ["API", "Interfaz para que dos programas hablen entre sí"],
        ["Hardware", "La parte física y tangible de la compu"],
        ["Software", "La parte lógica e intangible (programas)"],
        ["Hacker", "Experto que rompe o protege sistemas"],
        ["Ciberseguridad", "Defensa contra ataques digitales"],
        ["Router", "Dispositivo que dirige el tráfico WiFi"],
        ["Bug", "Error o bicho en el código"],
        ["Binario", "Lenguaje de ceros y unos"],
        ["Inteligencia Artificial", "Máquinas que simulan pensar"],
        ["HTML", "Lenguaje base para crear páginas web"],
        ["RAM", "Memoria temporal de acceso rápido"],
        ["CPU", "El cerebro del computador (procesador)"],
        ["Frontend", "La parte visual de una web que ves"],
        ["Backend", "La parte lógica del servidor que no ves"],
        ["Sistema Operativo", "Software principal como Windows o Linux"],
        ["Dirección IP", "Número que identifica tu PC en la red"],
        ["Encriptación", "Ocultar datos con clave secreta"],
        ["Framework", "Conjunto de herramientas listas para usar"],
        ["Compilador", "Traduce código humano a máquina"],
        ["Java", "Lenguaje popular y una isla o café"],
        ["Linux", "Sistema operativo del pingüino"],
        ["WiFi", "Internet inalámbrico"],
        ["Teclado", "Dispositivo de entrada con teclas"],
        ["Mouse", "Ratón para mover el cursor"],
        ["Monitor", "Pantalla para ver la imagen"],
        ["USB", "Conector universal para todo"],
        ["Blockchain", "Cadena de bloques (Bitcoin)"],
        ["Phishing", "Estafa por correo electrónico"],
        ["Cookie", "Archivo que rastrea tu navegación"]
    ],
    "🦁 Animales": [
        ["León", "Rey de la selva con melena"],
        ["Pingüino", "Ave de esmoquin que no vuela"],
        ["Elefante", "Grande, gris, orejón y con trompa"],
        ["Perro", "El mejor amigo del hombre"],
        ["Gato", "Felino doméstico independiente"],
        ["Tiburón", "Depredador del mar con aleta dorsal"],
        ["Jirafa", "El animal más alto, cuello largo"],
        ["Canguro", "Salta y tiene bolsa (Australia)"],
        ["Águila", "Ave rapaz con gran visión"],
        ["Dinosaurio", "Reptil gigante extinto"],
        ["Oso Polar", "Depredador blanco del hielo"],
        ["Tigre", "Felino grande con rayas"],
        ["Ballena", "Mamífero marino gigante"],
        ["Delfín", "Cetáceo inteligente y sonriente"],
        ["Gorila", "Primate grande y fuerte"],
        ["Mono", "Primate ágil que come bananas"],
        ["Serpiente", "Reptil largo sin patas"],
        ["Cocodrilo", "Reptil de río con gran mandíbula"],
        ["Hipopótamo", "Caballo de río gordo y peligroso"],
        ["Rinoceronte", "Tiene un cuerno en la nariz"],
        ["Cebra", "Caballo rayado blanco y negro"],
        ["Koala", "Come eucalipto y duerme mucho"],
        ["Panda", "Oso blanco y negro asiático"],
        ["Lobo", "Ancestro salvaje del perro, aúlla"],
        ["Zorro", "Cánido astuto y pequeño"],
        ["Camello", "Tiene jorobas y vive en el desierto"],
        ["Caballo", "Animal de monta y carrera"],
        ["Vaca", "Nos da leche y dice mu"],
        ["Cerdo", "Animal de granja rosado"],
        ["Gallina", "Pone huevos en la granja"],
        ["Pato", "Ave acuática que dice cuac"],
        ["Búho", "Ave nocturna de ojos grandes"],
        ["Murciélago", "Mamífero volador ciego"],
        ["Pulpo", "Marino con 8 tentáculos"],
        ["Cangrejo", "Camina de lado y tiene tenazas"],
        ["Mariposa", "Insecto de alas coloridas"],
        ["Abeja", "Produce miel"],
        ["Hormiga", "Insecto trabajador y fuerte"],
        ["Araña", "Teje telarañas y tiene 8 patas"],
        ["Escorpión", "Arácnido con aguijón venenoso"],
        ["Llama", "Camélido andino que escupe"],
        ["Perezoso", "Animal muy lento que se cuelga"]
    ],
    "🌍 Lugares": [
        ["Playa", "Arena, sol y mar"],
        ["Cine", "Pantalla gigante y películas"],
        ["Hospital", "Donde te curan los médicos"],
        ["Escuela", "Lugar donde vas a aprender"],
        ["Aeropuerto", "Pista de aviones y maletas"],
        ["Cementerio", "Lugar de descanso eterno"],
        ["Banco", "Donde se guarda el dinero"],
        ["Circo", "Payasos, carpa y acrobacias"],
        ["Estación Espacial", "Hogar fuera de la Tierra"],
        ["Supermercado", "Donde haces las compras de comida"],
        ["Biblioteca", "Silencio y muchos libros"],
        ["Gimnasio", "Lugar para hacer ejercicio y pesas"],
        ["Restaurante", "Lugar para comer fuera"],
        ["Hotel", "Hospedaje temporal con habitaciones"],
        ["Museo", "Exhibición de arte o historia"],
        ["Teatro", "Escenario para obras en vivo"],
        ["Zoológico", "Donde ves animales exóticos"],
        ["Farmacia", "Venta de medicinas"],
        ["Panadería", "Donde hornean pan fresco"],
        ["Cafetería", "Lugar para tomar café y charlar"],
        ["Universidad", "Estudios superiores"],
        ["Oficina", "Cubículos y trabajo administrativo"],
        ["Cárcel", "Donde encierran a los criminales"],
        ["Castillo", "Fortaleza de reyes y princesas"],
        ["Estadio", "Cancha grande para deportes"],
        ["Iglesia", "Lugar de culto religioso"],
        ["Parque de Diversiones", "Montañas rusas y juegos"],
        ["Submarino", "Nave que va bajo el agua"],
        ["Barco Pirata", "Nave con bandera de calavera"],
        ["Cueva", "Cavidad oscura en la tierra"],
        ["Desierto", "Lugar seco con mucha arena"],
        ["Selva", "Bosque denso tropical"],
        ["Polo Norte", "Lugar más al norte y frío"],
        ["Volcán", "Montaña que escupe fuego"],
        ["Isla", "Tierra rodeada de agua"],
        ["Faro", "Torre con luz para barcos"],
        ["Casino", "Juegos de azar y apuestas"],
        ["Discoteca", "Lugar para bailar y beber"]
    ],
    "🍔 Comida": [
        ["Pizza", "Masa redonda italiana con queso"],
        ["Sushi", "Arroz y pescado crudo japonés"],
        ["Hamburguesa", "Carne entre dos panes redondos"],
        ["Tacos", "Tortilla mexicana rellena"],
        ["Helado", "Postre frío y cremoso"],
        ["Chocolate", "Dulce oscuro de cacao"],
        ["Paella", "Arroz amarillo español con cosas"],
        ["Ensalada", "Mezcla saludable de vegetales"],
        ["Espagueti", "Pasta larga con salsa"],
        ["Hot Dog", "Salchicha en pan alargado"],
        ["Lasaña", "Capas de pasta, carne y queso"],
        ["Burrito", "Tortilla enrollada rellena"],
        ["Curry", "Plato especiado de la India"],
        ["Ramen", "Sopa de fideos japonesa"],
        ["Croissant", "Pan de hojaldre en forma de luna"],
        ["Donas", "Rosquilla dulce frita"],
        ["Papas Fritas", "Bastones de papa dorados"],
        ["Pollo Frito", "Ave apanada y crujiente"],
        ["Filete", "Corte noble de carne asada"],
        ["Sopa", "Caldo caliente con ingredientes"],
        ["Pastel", "Torta dulce de cumpleaños"],
        ["Galletas", "Discos dulces horneados"],
        ["Sándwich", "Emparedado de pan de molde"],
        ["Arroz Frito", "Arroz salteado estilo asiático"],
        ["Kebab", "Carne asada giratoria"],
        ["Nachos", "Triángulos de maíz con queso"],
        ["Quesadilla", "Tortilla doblada con queso fundido"],
        ["Fondue", "Olla de queso o chocolate derretido"],
        ["Cereal", "Desayuno con leche"],
        ["Yogur", "Lácteo fermentado cremoso"],
        ["Fruta", "Manzana, pera, banana, etc."],
        ["Verduras", "Zanahoria, brócoli, etc."],
        ["Huevo Frito", "Yema y clara cocinada en aceite"],
        ["Tostada", "Pan crujiente caliente"]
    ],
    "💼 Profesiones": [
        ["Médico", "Cura a los enfermos"],
        ["Policía", "Protege la ley y el orden"],
        ["Bombero", "Apaga incendios y rescata"],
        ["Astronauta", "Viaja al espacio exterior"],
        ["Profesor", "Enseña a los alumnos"],
        ["Abogado", "Defiende en juicios"],
        ["Payaso", "Hace reír con maquillaje"],
        ["Futbolista", "Juega profesionalmente al balón"],
        ["Cocinero", "Prepara alimentos profesionalmente"],
        ["Programador", "Escribe código para computadoras"],
        ["Mecánico", "Repara autos y motores"],
        ["Dentista", "Cuida y arregla los dientes"],
        ["Enfermero", "Asiste a médicos y pacientes"],
        ["Piloto", "Vuela aviones"],
        ["Carpintero", "Trabaja la madera"],
        ["Electricista", "Instala y repara la luz"],
        ["Fontanero", "Arregla tuberías y agua"],
        ["Granjero", "Cultiva la tierra y cría animales"],
        ["Científico", "Investiga y hace experimentos"],
        ["Pintor", "Crea arte con brocha o pinta casas"],
        ["Músico", "Toca instrumentos o canta"],
        ["Actor", "Interpreta personajes"],
        ["Escritor", "Escribe libros o historias"],
        ["Juez", "Dicta sentencias en la corte"],
        ["Soldado", "Sirve en el ejército"],
        ["Arquitecto", "Diseña edificios y casas"],
        ["Veterinario", "Médico de animales"],
        ["Mago", "Hace trucos de ilusión"],
        ["Detective", "Investiga crímenes y pistas"],
        ["Espía", "Agente secreto que se infiltra"],
        ["Fotógrafo", "Captura imágenes con cámara"],
        ["Periodista", "Investiga y reporta noticias"],
        ["Psicólogo", "Ayuda con la mente y emociones"],
        ["Sacerdote", "Líder religioso"],
        ["Político", "Gobierna o legisla"],
        ["Peluquero", "Corta y arregla el cabello"]
    ],
    "⚽ Deportes": [
        ["Fútbol", "Balón, 11 jugadores y portería"],
        ["Baloncesto", "Canasta alta y bote de balón"],
        ["Tenis", "Raqueta, red y pelota verde"],
        ["Voleibol", "Pasar el balón sobre la red con manos"],
        ["Natación", "Carreras en el agua"],
        ["Atletismo", "Correr, saltar y lanzar"],
        ["Ciclismo", "Carreras en bicicleta"],
        ["Boxeo", "Pelea con guantes en cuadrilátero"],
        ["Béisbol", "Bate, pelota y home run"],
        ["Golf", "Meter bola en hoyo con palo"],
        ["Rugby", "Balón ovalado y placajes"],
        ["Hockey", "Palo y disco sobre hielo o césped"],
        ["Esquí", "Deslizarse sobre nieve"],
        ["Surf", "Deslizarse sobre olas con tabla"],
        ["Karate", "Arte marcial de golpes y patadas"],
        ["Judo", "Arte marcial de llaves y caídas"],
        ["Gimnasia", "Acrobacias, flexibilidad y aparatos"],
        ["Fórmula 1", "Carreras de autos más rápidos"],
        ["Ajedrez", "Deporte mental de estrategia"],
        ["Ping Pong", "Tenis de mesa"],
        ["Bolos", "Derribar 10 pinos con bola pesada"],
        ["Tiro con Arco", "Flecha y diana"],
        ["Escalada", "Subir paredes verticales"]
    ],
    "🏠 Objetos de Casa": [
        ["Silla", "Sirve para sentarse"],
        ["Mesa", "Mueble para comer o trabajar"],
        ["Cama", "Mueble para dormir"],
        ["Sofá", "Asiento cómodo para varios"],
        ["Televisor", "Pantalla para ver programas"],
        ["Refrigeradora", "Mantiene la comida fría"],
        ["Lavadora", "Lava la ropa automáticamente"],
        ["Microondas", "Calienta comida rápido"],
        ["Espejo", "Te ves reflejado en él"],
        ["Lámpara", "Da luz artificial"],
        ["Reloj", "Marca la hora"],
        ["Teléfono", "Para llamar y mensajear"],
        ["Computadora", "Máquina para trabajar y navegar"],
        ["Llaves", "Abren puertas y cerraduras"],
        ["Billetera", "Guarda dinero y documentos"],
        ["Mochila", "Bolsa para cargar cosas en la espalda"],
        ["Gafas", "Protegen los ojos o mejoran vista"],
        ["Paraguas", "Te protege de la lluvia"],
        ["Plato", "Donde sirves la comida"],
        ["Cuchara", "Para tomar sopa"],
        ["Cuchillo", "Para cortar carne"],
        ["Tenedor", "Para pinchar la comida"],
        ["Vaso", "Para beber líquidos"],
        ["Sartén", "Para freír cosas"],
        ["Olla", "Para cocinar sopas o guisos"],
        ["Escoba", "Para barrer el suelo"],
        ["Basurero", "Donde tiras los desechos"],
        ["Toalla", "Para secarse el cuerpo"],
        ["Jabón", "Para lavar y limpiar"],
        ["Papel Higiénico", "Rollo de baño"]
    ],
    "🦵 Cuerpo Humano": [
        ["Cabeza", "Parte superior donde está el cerebro"],
        ["Ojos", "Órganos para ver"],
        ["Nariz", "Órgano para oler y respirar"],
        ["Boca", "Para comer y hablar"],
        ["Orejas", "Órganos para escuchar"],
        ["Pelo", "Cubre la cabeza (o no)"],
        ["Corazón", "Bombea sangre"],
        ["Pulmones", "Órganos para respirar aire"],
        ["Estómago", "Donde se digiere la comida"],
        ["Manos", "Tienen dedos y agarran cosas"],
        ["Pies", "Sirven para caminar"],
        ["Huesos", "Forman el esqueleto duro"],
        ["Sangre", "Líquido rojo vital"],
        ["Cerebro", "Órgano que piensa"],
        ["Dientes", "Sirven para masticar"],
        ["Lengua", "Órgano del gusto"],
        ["Dedos", "Extremidades de las manos"],
        ["Uñas", "Protección dura en los dedos"],
        ["Piel", "El órgano más grande que cubre todo"],
        ["Músculos", "Permiten el movimiento"],
        ["Rodilla", "Articulación de la pierna"],
        ["Codo", "Articulación del brazo"],
        ["Cuello", "Sostiene la cabeza"],
        ["Espalda", "Parte trasera del torso"]
    ],
    "🚗 Transporte": [
        ["Coche", "Vehículo de 4 ruedas personal"],
        ["Bicicleta", "Dos ruedas y pedales"],
        ["Moto", "Dos ruedas y motor"],
        ["Avión", "Vuela por el aire"],
        ["Barco", "Flota y navega en agua"],
        ["Tren", "Va sobre rieles"],
        ["Autobús", "Transporte público grande"],
        ["Taxi", "Coche de alquiler con chofer"],
        ["Helicóptero", "Vuela con hélices arriba"],
        ["Camión", "Transporta carga pesada"],
        ["Patineta", "Tabla con ruedas"],
        ["Submarino", "Viaja bajo el agua"],
        ["Globo", "Vuela con aire caliente"],
        ["Cohete", "Viaja al espacio"],
        ["Metro", "Tren subterráneo urbano"],
        ["Teleférico", "Cabina colgada de un cable"],
        ["Caballo", "Transporte animal clásico"],
        ["Limusina", "Coche muy largo y lujoso"]
    ],
    "🎬 Películas y Series": [
        ["Star Wars", "Guerra de las galaxias, sables de luz"],
        ["Harry Potter", "Mago con cicatriz y varita"],
        ["El Señor de los Anillos", "Hobbits, anillo y volcán"],
        ["Titanic", "Barco gigante que se hunde"],
        ["El Rey León", "Hakuna Matata, Simba"],
        ["Avengers", "Superhéroes juntos salvando el mundo"],
        ["Batman", "Caballero de la noche, murciélago"],
        ["Spiderman", "Hombre araña, trepa muros"],
        ["Joker", "Payaso villano de Ciudad Gótica"],
        ["Shrek", "Ogro verde y burro parlante"],
        ["Toy Story", "Juguetes que cobran vida"],
        ["Frozen", "Libre soy, hielo y reina Elsa"],
        ["Coco", "Día de muertos, guitarra y abuela"],
        ["El Padrino", "Mafia italiana, oferta irresistible"],
        ["Matrix", "Simulación, pastilla roja o azul"],
        ["Jurassic Park", "Parque de dinosaurios vivos"],
        ["Volver al Futuro", "Viajes en el tiempo en un DeLorean"],
        ["Forrest Gump", "Corre Forrest, caja de chocolates"]
    ]
};